name: fuel_app
description: "A new Flutter project connected to Django backend."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # Social Auth
  sign_in_with_apple: ^5.0.0
  google_sign_in: ^6.2.1

  # HTTP & Storage
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

  # Maps & Launcher
  google_maps_flutter: ^2.5.0
  url_launcher: ^6.1.10

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  meta: 1.18.1
  matcher: 0.12.19
  test_api: 0.7.10

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/car.png
    - assets/images/city.png
    - assets/images/stabex.png
    - assets/images/shell.png
    - assets/images/total.png
    - assets/images/rubis.png
    - assets/images/station.png
    - assets/images/avatar.png
    - assets/images/petrol.png
    - assets/images/diesel.png
    - assets/images/kerosene.png
    - assets/images/shell_station.png
    - assets/images/stabex_station.png
    - assets/images/total_station.png
    - assets/images/Rubis_station.png
    - assets/images/wave.png
    - assets/images/shel.png
    - assets/images/stabe.png
    - assets/images/Totall.png
    - assets/images/cityoil.png
    - assets/images/Rubi.png
    - assets/images/map.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700