import 'package:flutter/material.dart';
import 'package:latlong2/latlong.dart' hide Path;
import 'station_model.dart';
import 'fuel_type_model.dart';

final List<FuelType> kFuelTypes = [
  const FuelType(id: '1', name: 'V-Power', icon: '⚡', color: Color(0xFFC4963D)),
  const FuelType(id: '2', name: 'Petrol 98', icon: '⛽', color: Color(0xFFFF8C00)),
  const FuelType(id: '3', name: 'Diesel', icon: '🛢️', color: Color(0xFFFF8C00)),
  const FuelType(id: '4', name: 'Kerosene', icon: '💧', color: Color(0xFFFF8C00)),
  const FuelType(id: '5', name: 'LPG', icon: '🔥', color: Color(0xFFFF8C00)),
  const FuelType(id: '6', name: 'Electric', icon: '⚡', color: Color(0xFFFF8C00)),
];

final List<FuelStation> kStations = [
  FuelStation(
    id: '1',
    name: 'Shell Ntinda',
    address: 'Ntinda Road, Kampala',
    rating: 4.6,
    reviewCount: 342,
    distance: '0.3 km',
    imageUrl: 'assets/images/Shel.png',
    position: const LatLng(0.3476, 32.5825),
    isOpen: true,
    pricePerLitre: 'UGX 4,850',
    fuelTypes: ['Petrol 95', 'Petrol 98', 'Diesel'],
    phone: '+256 414 123456',
    openingHours: '24 Hours',
  ),
  FuelStation(
    id: '2',
    name: 'TotalEnergies',
    address: 'Kampala Road, Kampala',
    rating: 4.5,
    reviewCount: 289,
    distance: '0.7 km',
    imageUrl: 'assets/images/Totall.png',
    position: const LatLng(0.3460, 32.5840),
    isOpen: true,
    pricePerLitre: 'UGX 4,800',
    fuelTypes: ['Petrol 95', 'Diesel', 'Kerosene'],
    phone: '+256 414 234567',
    openingHours: '6:00 AM - 10:00 PM',
  ),
  FuelStation(
    id: '3',
    name: 'Stabex',
    address: 'Jinja Road, Kampala',
    rating: 4.3,
    reviewCount: 156,
    distance: '1.1 km',
    imageUrl: 'assets/images/Stabe.png',
    position: const LatLng(0.3490, 32.5810),
    isOpen: false,
    pricePerLitre: 'UGX 4,780',
    fuelTypes: ['Petrol 95', 'Diesel', 'LPG'],
    phone: '+256 414 345678',
    openingHours: '7:00 AM - 9:00 PM',
  ),
  FuelStation(
    id: '4',
    name: 'Rubis',
    address: 'Bombo Road, Kampala',
    rating: 4.4,
    reviewCount: 198,
    distance: '1.5 km',
    imageUrl: 'assets/images/Rubi.png',
    position: const LatLng(0.3510, 32.5800),
    isOpen: true,
    pricePerLitre: 'UGX 4,820',
    fuelTypes: ['Petrol 95', 'Petrol 98', 'Diesel', 'Electric'],
    phone: '+256 414 456789',
    openingHours: '24 Hours',
  ),
  FuelStation(
    id: '5',
    name: 'City Oil',
    address: 'Entebbe Road, Kampala',
    rating: 4.2,
    reviewCount: 134,
    distance: '2.0 km',
    imageUrl: 'assets/images/cityoil.png',
    position: const LatLng(0.3445, 32.5790),
    isOpen: true,
    pricePerLitre: 'UGX 4,790',
    fuelTypes: ['Petrol 95', 'Diesel', 'Kerosene'],
    phone: '+256 414 567890',
    openingHours: '6:00 AM - 11:00 PM',
  ),
];
