/// This file is generated by the FlutterFire CLI.
/// It contains Firebase configuration for each platform.
/// Replace the placeholder values with your actual Firebase project credentials.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // TODO: Replace the following placeholder values with your Firebase project configuration.
    // For Web (Chrome) platform:
    return const FirebaseOptions(
      apiKey: 'YOUR_API_KEY',
      authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
      projectId: 'YOUR_PROJECT_ID',
      storageBucket: 'YOUR_PROJECT_ID.appspot.com',
      messagingSenderId: 'YOUR_SENDER_ID',
      appId: 'YOUR_APP_ID',
      measurementId: 'YOUR_MEASUREMENT_ID',
    );
  }
}
